name: Docker Build and Push

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '1 1 * * 0'

env:
  BUILD_BERSION: "2.2.2-cuda12.1-cudnn8-runtime"

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: self-hosted
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Log in to GitHub registry
      #   uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Log in to Tencent registry GZ
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.DOCKER_USERNAME_TENCENT }}
          password: ${{ secrets.DOCKER_PASSWORD_TENCENT }}

      # - name: Log in to Tencent registry USW
      #   uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      #   with:
      #     registry: uswccr.ccs.tencentyun.com
      #     username: ${{ secrets.DOCKER_USERNAME_TENCENT }}
      #     password: ${{ secrets.DOCKER_PASSWORD_TENCENT }}

      # # GITHUB_REPOSITORY_OWNER

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            # dockerflays/pytorch
            ccr.ccs.tencentyun.com/dockerflays/pytorch
          tags: |
            ${{ env.BUILD_BERSION }}
            type=sha,enable=true,priority=100,prefix=sha-,suffix=,format=short
            type=raw,value=action-{{branch}}-{{date 'YYYYMMDD-HHmmss' tz='Asia/Shanghai'}}
          labels: |
            maintainer=DockerFlys
            org.opencontainers.image.title=pytorch
            org.opencontainers.image.description=pytorch images update default mirrors
            org.opencontainers.image.vendor=DockerFlys
            org.opencontainers.image.version=${{ env.BUILD_BERSION }}


      - name: Build and push Docker images
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./pytorch/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
